site_name: A Guide to Setting Up a Research Environment for Many-Body Computations
site_url: https://chriswenchen.github.io/guide-env-setup/
use_directory_urls: true

theme:
  name: material
  language: en

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 中文
          build: true
          site_name: 多体计算研究环境搭建指南
          nav:
            - 首页: index.md
            - 网盘与文件同步: sync.md
  - macros

nav:
  - Home: index.md
  - Cloud Storage and File Synchronization: sync.md



extra:
  alternate:
    - name: English
      link: /guide-env-setup/
      lang: en
    - name: 中文
      link: /guide-env-setup/zh/
      lang: zh
  version: 3.0.0
  release_date: 2026-02-14
  author: Wen Chen
  email: "wenchenphy@gmail.com"